import Foundation

print("JorvikDailyNews tests")
print("")

VideoLinkTests.run()
PDFContentTypeTests.run()
PDFPageSizesTests.run()
SVGSafetyTests.run()
VideoPreflightTests.run()
ReaderLedeTests.run()
RedirectGuardTests.run()
OPMLImportTests.run()
VideoIDTests.run()
FeedFetcherTests.run()
FeedBoundsTests.run()
StandfirstTests.run()
StandfirstLimitTests.run()
TitleDecodeTests.run()
EditionBuilderTests.run()
PagePicturesTests.run()
BlankPictureTests.run()
DayRolloverTests.run()
WebURLTests.run()
ReaderLinkTests.run()
MailtoLinkTests.run()
EmbeddedArticleTests.run()
WalkerTests.run()
ReaderBlockTests.run()
LegacyIDTests.run()
BaseHrefTests.run()
await QuadraticTests.run()

exit(T.report())
